const express = require('express')
const router = express.Router()
const { registraUsuario, compruebaUsuario, eliminaUsuario, cambiaPassword } = require('../controllers/auth')
const { getItems, getItemsCount, createItem, deleteItem, editItem, editdragItem, actualizarOrdenElementos, getNameByUrl, moveItem, getItem, setNotes, setLinkImg, setImages, deleteImage, obtenerStatus, encontrarDuplicadosPorURL, getAllItems } = require('../controllers/links')
const { authMiddleware } = require('../middleware/session')
const { getDeskItems, testTemplates } = require('../controllers/escritorios')
const { validateCreateLink, validateEditLink } = require('../validators/links')
router.get('/', (req, res) => {
  res.render('landing.pug')
})
router.get('/linkStatus', authMiddleware, obtenerStatus)
router.get('/link', authMiddleware, getItem)
router.get('/links', authMiddleware, getItems)
router.get('/allLinks', authMiddleware, getAllItems)
router.get('/templates', authMiddleware, testTemplates)
router.get('/duplicados', authMiddleware, encontrarDuplicadosPorURL)
router.get('/linksCount', getItemsCount)
router.get('/linkName', authMiddleware, getNameByUrl)
router.get('/escritorios', getDeskItems)
router.post('/register', registraUsuario)
router.post('/login', compruebaUsuario)
router.post('/', createItem)
router.post('/links', authMiddleware, validateCreateLink, createItem)
router.post('/linkNotes', authMiddleware, setNotes)
router.delete('/deleteImg', authMiddleware, deleteImage)
router.delete('/links', authMiddleware, deleteItem)
router.put('/links', authMiddleware, validateEditLink, editItem)
router.put('/draglinks', editdragItem)
router.put('/draglink', actualizarOrdenElementos)
router.put('/moveLinks', authMiddleware, moveItem)
module.exports = router
