const express = require('express')
const router = express.Router()
const multer = require('multer')
const upload = multer()
const { registraUsuario, compruebaUsuario, eliminaUsuario, cambiaPassword } = require('../controllers/auth')
const { getItems, getItemsCount, createItem, deleteItem, editItem, editdragItem, actualizarOrdenElementos, getNameByUrl, moveItem, getItem, setNotes, obtenerStatus, encontrarDuplicadosPorURL, getAllItems } = require('../controllers/links')
const { getDeskItems, deleteDeskItem, createDeskItem, editDeskItem, testTemplates, ordenaDesks, cagadasFix, getSidePanel } = require('../controllers/escritorios')
const { authMiddleware } = require('../middleware/session')
const { validateCreateLink, validateEditLink } = require('../validators/links')
const { validateEditColumn, validateCreateColumn } = require('../validators/columnas')
const { validateEditDesktop, validateCreateDesktop } = require('../validators/escritorios')
const { getColItems, createColItem, deleteColItem, editColItem, actualizarOrdenColumnas, moveColumns } = require('../controllers/columnas')
const { displayUserProfile } = require('../controllers/users')
const { searchLinks } = require('../controllers/searchController')
const { uploadProfileImage, uploadLinkIcon, uploadImg, deleteImg, backup, downloadBackup, getBackgroundUrl } = require('../helpers/storage')

router.get('/', (req, res) => {
  res.render('landing.pug')
})

router.get('/:nombre', authMiddleware, testTemplates)
router.get('/api/cagadas', cagadasFix)

router.get('/api/linkStatus', authMiddleware, obtenerStatus)
router.get('/api/columnas', getColItems)
router.get('/api/link', authMiddleware, getItem)
router.get('/api/links', authMiddleware, getItems)
router.get('/api/allLinks', authMiddleware, getAllItems)
router.get('/api/templates', authMiddleware, testTemplates)
router.get('/api/duplicados', authMiddleware, encontrarDuplicadosPorURL)
router.get('/api/linksCount', getItemsCount)
router.get('/api/linkName', authMiddleware, getNameByUrl)
router.get('/api/escritorios', getDeskItems)
router.get('/api/sidepanel', authMiddleware, getSidePanel)
router.get('/api/search', authMiddleware, searchLinks)
router.get('/api/deleteUser', authMiddleware, eliminaUsuario)
router.get('/api/profile', authMiddleware, displayUserProfile)
router.get('/api/downloadBackup', authMiddleware, downloadBackup)
router.get('/api/getBackground', authMiddleware, getBackgroundUrl)
router.post('/api/changePassword', authMiddleware, cambiaPassword)
// router.post('/register', registraUsuario)
router.post('/login', compruebaUsuario) // Va a fallar
router.post('/api/', createItem)
router.post('/api/links', authMiddleware, validateCreateLink, createItem)
router.post('/api/columnas', authMiddleware, validateCreateColumn, createColItem)
router.post('/api/escritorios', authMiddleware, validateCreateDesktop, createDeskItem)
router.post('/api/linkNotes', authMiddleware, setNotes)
router.post('/api/backup', authMiddleware, backup)
router.post('/api/uploadImgProfile', authMiddleware, upload.single('file'), uploadProfileImage)
router.post('/api/uploadLinkImg', authMiddleware, upload.single('linkImg'), uploadLinkIcon)
router.post('/api/uploadImg', authMiddleware, upload.single('images'), uploadImg)
router.delete('/api/deleteImg', authMiddleware, deleteImg)
router.delete('/api/links', authMiddleware, deleteItem)
router.delete('/api/columnas', authMiddleware, deleteColItem)
router.delete('/api/escritorios', authMiddleware, deleteDeskItem)
router.put('/api/links', authMiddleware, validateEditLink, editItem)
router.put('/api/columnas', authMiddleware, validateEditColumn, editColItem)
router.put('/api/escritorios', authMiddleware, validateEditDesktop, editDeskItem)
router.put('/api/draglinks', editdragItem)
router.put('/api/draglink', actualizarOrdenElementos)
router.put('/api/dragcol', actualizarOrdenColumnas)
router.put('/api/ordenaDesks', authMiddleware, ordenaDesks)
router.put('/api/moveLinks', authMiddleware, moveItem)
router.put('/api/moveCols', authMiddleware, moveColumns)
module.exports = router
